name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  export-game:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'macOS', 'Windows Desktop', 'Linux/X11', 'Web' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Project Data
        uses: actions/cache@v4
        with:
          path: ~/.cache/godot
          key: ${{ runner.os }}-godot-cache-${{ hashFiles('**/project.godot') }}

      # This is the corrected build step using the action's proper inputs
      - name: Build and Export
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          # Tell the action which export preset to use (from your export_presets.cfg)
          export_preset: "${{ matrix.platform }}"
          # Tell the action where to put the exported files
          export_path: "build/${{ matrix.platform }}/BoxBattle"

      - name: Prepare Artifact
        run: |
          # This step no longer needs to call 'godot' because the build is already done.
          # We just need the version number for naming the zip file.
          VERSION=$(grep "application/config/version" project.godot | cut -d'"' -f2)
          echo "Project version is $VERSION"
          
          cd build
          zip -r BoxBattle-v$VERSION-${{ matrix.platform }}.zip ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: build/BoxBattle-v*.zip # Wildcard still works great here