name: Build and Export Godot 4.4.1 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preset: [Linux/X11, Windows Desktop, macOS, Web]
        include:
          - preset: Linux/X11
            runner: ubuntu-latest
            suffix: linux
          - preset: Windows Desktop
            runner: ubuntu-latest
            suffix: windows
          - preset: macOS
            runner: ubuntu-latest
            suffix: macOS
          - preset: Web
            runner: ubuntu-latest
            suffix: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from project.godot
        id: get_version
        run: |
          version=$(grep -E '^config/version=' project.godot | head -n1 | cut -d'=' -f2 | tr -d '"')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Export Game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
          preset: ${{ matrix.preset }}
          archive_output: true
          cache: true

      - name: Rename Export Zip
        run: |
          mv build/${{ matrix.preset }}.zip BoxBattle-v${{ env.VERSION }}-${{ matrix.suffix }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BoxBattle-v${{ env.VERSION }}-${{ matrix.suffix }}.zip
          path: BoxBattle-v${{ env.VERSION }}-${{ matrix.suffix }}.zip