name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  export-game:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'macOS', 'Windows Desktop', 'Linux/X11', 'Web' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Project Data
        uses: actions/cache@v4
        with:
          path: ~/.cache/godot
          key: ${{ runner.os }}-godot-cache-${{ hashFiles('**/project.godot') }}

      - name: Build and Export
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          # Explicitly tell the action which program to run.
          entryPoint: 'godot'
          # Pass all arguments as a single string. Quotes are critical.
          args: --headless --export-release "${{ matrix.platform }}" "build/${{ matrix.platform }}/BoxBattle"

      - name: Prepare Artifact
        run: |
          # Get version from project.godot (this part was working correctly)
          VERSION=$(grep "application/config/version" project.godot | cut -d'"' -f2)
          echo "Project version is $VERSION"
          
          # Zip the output directory into a versioned archive
          cd build
          # CRITICAL FIX: Add quotes around the platform names to handle spaces
          zip -r "BoxBattle-v$VERSION-${{ matrix.platform }}.zip" "${{ matrix.platform }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ steps.get_version.outputs.VERSION }}
          # Use a wildcard that correctly handles the space in the filename
          path: build/BoxBattle-v*.zip