# Fixed Godot CI Workflow using firebelley/godot-export
name: Godot CI
on:
  push:
    branches: [ "main" ]

jobs:
  export-game:
    name: Export Game
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://sourceforge.net/projects/godot-engine.mirror/files/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip/download
          godot_export_templates_download_url: https://sourceforge.net/projects/godot-engine.mirror/files/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz/download
          relative_project_path: ./
          archive_output: true
          verbose: true
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-builds
          path: ${{ steps.export.outputs.archive_directory }}/*