name: Godot CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Export Templates
        run: |
          # Download templates
          wget -O export_templates.tpz https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          # Create a temporary directory and the final destination
          mkdir -p /tmp/templates-unzipped
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          # Unzip to the temporary directory
          unzip export_templates.tpz -d /tmp/templates-unzipped
          # Move the *contents* of the inner 'templates' folder to the correct location
          mv /tmp/templates-unzipped/templates/* ~/.local/share/godot/export_templates/4.4.1.stable
          # Verify files are in the correct place for debugging
          echo "Verifying contents of export templates directory:"
          ls -l ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Setup build directory
        run: mkdir -vp build/windows
      - name: Build and Export for Windows
        run: godot --headless --verbose --export-release "Windows Desktop" "build/windows/BOX BATTLE.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows

  # The same template installation logic is applied to all other jobs...
  build-web:
    name: Build for Web
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Export Templates
        run: |
          wget -O export_templates.tpz https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          mkdir -p /tmp/templates-unzipped
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          unzip export_templates.tpz -d /tmp/templates-unzipped
          mv /tmp/templates-unzipped/templates/* ~/.local/share/godot/export_templates/4.4.1.stable
          ls -l ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Setup build directory
        run: mkdir -vp build/web
      - name: Build and Export for Web
        run: godot --headless --verbose --export-release "Web" "build/web/index.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  build-mac:
    name: Build for macOS
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Export Templates
        run: |
          wget -O export_templates.tpz https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          mkdir -p /tmp/templates-unzipped
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          unzip export_templates.tpz -d /tmp/templates-unzipped
          mv /tmp/templates-unzipped/templates/* ~/.local/share/godot/export_templates/4.4.1.stable
          ls -l ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Setup build directory
        run: mkdir -vp build/macos
      - name: Build and Export for macOS
        run: godot --headless --verbose --export-release "macOS" "build/macos/BOX BATTLE.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Export Templates
        run: |
          wget -O export_templates.tpz https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          mkdir -p /tmp/templates-unzipped
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          unzip export_templates.tpz -d /tmp/templates-unzipped
          mv /tmp/templates-unzipped/templates/* ~/.local/share/godot/export_templates/4.4.1.stable
          ls -l ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Setup build directory
        run: mkdir -vp build/linux
      - name: Build and Export for Linux
        run: godot --headless --verbose --export-release "Linux" "build/linux/BOX BATTLE.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-web, build-mac, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-build/*
            artifacts/web-build/*
            artifacts/macos-build/*
            artifacts/linux-build/*