name: Build and Export Godot Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  export-game:
    runs-on: ubuntu-latest
    name: Build and Export All Platforms

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Project Version
        id: get_version
        run: |
          VERSION=$(grep "application/config/version" project.godot | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Export
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: "https://godotengine.org/download/archive/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://godotengine.org/download/archive/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz"
          relative_project_path: "./"
          presets_to_export: "macOS,Windows Desktop,Linux/X11,Web"
          archive_output: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-builds-v${{ steps.get_version.outputs.VERSION }}
          path: ${{ steps.export.outputs.archive_directory }}
