name: Godot CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-macos:
    name: Build for macOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for macOS
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          export_preset: 'macOS'
          build_path: 'build/macos'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for Linux
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          export_preset: 'Linux'
          build_path: 'build/linux'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux

  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for Windows
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          export_preset: 'Windows Desktop'
          build_path: 'build/windows'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows

  build-web:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for Web
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          export_preset: 'Web'
          build_path: 'build/web'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  package-builds:
    name: Package All Builds
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux, build-windows, build-web]
    steps:
      - name: Download macOS Build
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: package/macos

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: package/linux

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: package/windows

      - name: Download Web Build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: package/web

      - name: Zip the package
        run: zip -r game-builds.zip package

      - name: Upload Final Package
        uses: actions/upload-artifact@v4
        with:
          name: game-builds
          path: game-builds.zip