name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  export-game:
    # This single job will build all platforms
    runs-on: ubuntu-latest
    name: Build and Export Game

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export All Platforms
        id: export # Give this step an ID to reference its output
        uses: firebelley/godot-export@v6.0.0 # Use the latest correct version
        with:
          # --- Required Inputs from the Documentation ---
          godot_executable_download_url: "https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_export_templates.tpz"
          relative_project_path: "./"
          
          # --- Our Configuration ---
          # A comma-separated list of the exact names from your export_presets.cfg
          presets_to_export: "macOS,Windows Desktop,Linux/X11,Web"
          # Tell the action to create .zip files for us
          archive_output: true
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          # The name for the collection of build artifacts
          name: game-builds
          # The path to the directory containing the zip files the action just created
          path: ${{ steps.export.outputs.archive_directory }}