# .github/workflows/main.yml

name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Use environment variables to avoid repeating the URLs in every job
env:
  GODOT_EXECUTABLE_URL: "https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip"
  GODOT_TEMPLATES_URL: "https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz"

jobs:
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for Windows
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: ${{ env.GODOT_EXECUTABLE_URL }}
          godot_export_templates_download_url: ${{ env.GODOT_TEMPLATES_URL }}
          relative_project_path: "./"
          presets_to_export: "Windows Desktop" # Note: Only one preset per job
          # The action will place the build in a directory named 'exports' by default
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: exports/ # Upload the entire 'exports' directory

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for Linux
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: ${{ env.GODOT_EXECUTABLE_URL }}
          godot_export_templates_download_url: ${{ env.GODOT_TEMPLATES_URL }}
          relative_project_path: "./"
          presets_to_export: "Linux"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: exports/

  build-web:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Export for Web
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: ${{ env.GODOT_EXECUTABLE_URL }}
          godot_export_templates_download_url: ${{ env.GODOT_TEMPLATES_URL }}
          relative_project_path: "./"
          presets_to_export: "Web"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: exports/

  build-macos:
    name: Build for macOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This is the critical step that fixes the macOS build failure on Linux runners
      - name: Install macOS DMG creation tools
        run: sudo apt-get update && sudo apt-get install -y genisoimage

      - name: Build and Export for macOS
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: ${{ env.GODOT_EXECUTABLE_URL }}
          godot_export_templates_download_url: ${{ env.GODOT_TEMPLATES_URL }}
          relative_project_path: "./"
          presets_to_export: "macOS"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: exports/

  package-builds:
    name: Package All Builds
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-web, build-macos]
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: package/windows

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: package/linux

      - name: Download Web Build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: package/web
          
      - name: Download macOS Build
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: package/macos

      - name: Zip the package
        run: zip -r game-builds.zip package

      - name: Upload Final Package
        uses: actions/upload-artifact@v4
        with:
          name: game-builds
          path: game-builds.zip