name: Godot CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1-stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup build directory
        run: mkdir -v build/windows
      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Build and Export for Windows
        run: godot --headless --verbose --export-release "Windows Desktop" "build/windows/BOX BATTLE.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows

  build-mac:
    name: Build for macOS
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1-stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup build directory
        run: mkdir -v build/macos
      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Build and Export for macOS
        # Note: The output from the container will be a .zip, not a .dmg. This is a limitation of building on Linux.
        # To create a proper .dmg, the build job would need to run on a macOS runner.
        run: godot --headless --verbose --export-release "macOS" "build/macos/BOX BATTLE.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1-stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup build directory
        run: mkdir -v build/linux
      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Build and Export for Linux
        run: godot --headless --verbose --export-release "Linux" "build/linux/BOX BATTLE.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux

  build-web:
    name: Build for Web
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1-stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup build directory
        run: mkdir -v build/web
      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.1.stable ~/.local/share/godot/export_templates/4.4.1.stable
      - name: Build and Export for Web
        run: godot --headless --verbose --export-release "Web" "build/web/index.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web