name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  export-game:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add 'Web' to the list of platforms to build for.
        platform: [ 'macOS', 'Windows Desktop', 'Linux/X11', 'Web' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Godot Project Data
        uses: actions/cache@v4
        with:
          path: ~/.cache/godot
          key: ${{ runner.os }}-godot-cache-${{ hashFiles('**/project.vot') }}

      - name: Build and Export
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          args: --headless --export-release "${{ matrix.platform }}" "build/${{ matrix.platform }}/BoxBattle"

      - name: Prepare Artifact
        run: |
          VERSION=$(godot --headless --script .github/scripts/get_version.gd)
          echo "Project version is $VERSION"
          
          cd build
          zip -r BoxBattle-v$VERSION-${{ matrix.platform }}.zip ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ steps.get_version.outputs.VERSION }}
          path: build/BoxBattle-v*.zip