name: Godot CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # This single step now handles setting up Godot, downloading templates,
      # and running the export build, which validates the entire project.
      - name: Build and Export for macOS
        uses: abarichello/godot-ci@4.4.1-stable
        with:
          # The name of the export preset in your export_presets.cfg file.
          export_preset: 'macOS'
          # The directory where the build artifact will be placed.
          build_path: 'build/macos'